---
name: digital-scale
board: boards/red-pitaya
version: 0.1.0

cores:
  - fpga/cores/axi_ctl_register_v1_0
  - fpga/cores/axi_sts_register_v1_0
  - fpga/cores/redp_adc_v1_0
  - fpga/cores/redp_dac_v1_0

memory:
  - name: control
    offset: '0x60000000'
    range: 4K
  - name: status
    offset: '0x50000000'
    range: 4K

control_registers:
  - dds_freq_hz
  - led

status_registers:
  - adc_amplitude

parameters:
  fclk0: 125000000

xdc:
  - boards/red-pitaya/config/ports.xdc
  - boards/red-pitaya/config/clocks.xdc

drivers:
  - server/drivers/common.hpp
  - ./scale.hpp

web:
  - ./web/index.html
  - ./web/scale.html
  - web/koheron.ts
  - ./web/scale.ts
  - ./web/app.ts
  - ./web/navigation.html
  - web/plot-basics/plot-basics.html
  - ./web/plot/yunit.html
  - ./web/fft/fft-window.html
  - ./web/fft/input-channel.html
  - ./web/plot/peak-detection.html
  - web/dds-frequency/dds-frequency.html
  - ./web/export-file/export-file.html
  - web/laser-control.html
  - web/main.css
