---
name: scale-ml
board: boards/red-pitaya
version: 0.3.0

cores:
  - fpga/cores/redp_adc_v1_0
  - fpga/cores/redp_dac_v1_0
  - fpga/cores/axi_ctl_register_v1_0
  - fpga/cores/axi_sts_register_v1_0
  - fpga/cores/edge_detector_v1_0
  - fpga/cores/comparator_v1_0
  - ../scale/address_counter_v1_0

memory:
  - name: control
    offset: '0x60000000'
    range: 4K
  - name: status
    offset: '0x50001000'
    range: 4K
  - name: xadc
    offset: '0x43C00000'
    range: 64K
  - name: adc
    range: 64K
    offset: '0x40000000'
  - name: dac
    range: 64K
    offset: '0x40040000'

control_registers:
  - led
  - trig

status_registers:
  - reg1

parameters:
  fclk0: 200000000
  adc_clk: 125000000

xdc:
  - boards/red-pitaya/config/ports.xdc
  - boards/red-pitaya/config/clocks.xdc

drivers:
  - server/drivers/common.hpp
  - ./driver.hpp

web:
  - web/koheron.ts
  - web/jquery.flot.d.ts
  - ./web/app.ts
  - web/main.css
  - ../scale/web/connector.ts
  - ../scale/web/plot-basics.ts
  - ../scale/web/plot-basics.html
  - ../scale/web/index.html
  - ../scale/web/scale.html
  - ./web/ml.html
